import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { environment } from 'src/environments/environment';
import { User } from '../_models/user';

@Injectable({
  providedIn: 'root'
})
export class UserService {

  constructor(private http: HttpClient) { }

  getAll() {
    return this.http.get<User[]>(`${environment.apiUrl}/posts`);
  }

  getById(id) {
    return this.http.get<User[]>(`${environment.apiUrl}/users/${id}`);
  }

  getEmailValid() {
    return [
      "1033edge.com",
      "11mail.com",
      "123.com",
      "123box.net",
      "123india.com",
      "123mail.cl",
      "123qwe.co.uk",
      "126.com",
      "150ml.com",
      "15meg4free.com",
      "163.com",
      "1coolplace.com",
      "1freeemail.com",
      "1funplace.com",
      "1internetdrive.com",
      "1mail.net",
      "1me.net",
      "1mum.com",
      "1musicrow.com",
      "1netdrive.com",
      "1nsyncfan.com",
      "1under.com",
      "1webave.com",
      "1webhighway.com",
      "212.com",
      "24horas.com",
      "2911.net",
      "2bmail.co.uk",
      "2d2i.com",
      "2die4.com",
      "3000.it",
      "321media.com",
      "37.com",
      "3ammagazine.com",
      "3dmail.com",
      "3email.com",
      "3xl.net",
      "444.net",
      "4email.com",
      "4email.net",
      "4mg.com",
      "4newyork.com",
      "4x4man.com",
      "5iron.com",
      "5star.com",
      "88.am",
      "8848.net",
      "888.nu",
      "97rock.com",
      "aaamail.zzn.com",
      "aamail.net",
      "billsfan.net",
      "bimamail.com",
      "bimla.net",
      "birdowner.net",
      "bisons.com",
      "bitmail.com",
      "bitpage.net",
      "bizhosting.com",
      "bla-bla.com",
      "blackburnmail.com",
      "blackplanet.com",

      "fuse.net",
      "fut.es",
      "fwnb.com",
      "fxsmails.com",
      "galamb.net",
      "galaxy5.com",
      "gamebox.net",
      "gamegeek.com",
      "games.com",
      "gamespotmail.com",
      "garbage.com",
      "gardener.com",
      "gateway.net",
      "gawab.com",
      "gaybrighton.co.uk",
      "gaza.net",
      "gazeta.pl",
      "gazibooks.com",
      "gci.net",
      "gee-wiz.com",
      "geecities.com",
      "geek.com",
      "geek.hu",
      "geeklife.com",
      "general-hospital.com",
      "geocities.com",
      "geologist.com",
      "geopia.com",
      "gh2000.com",
      "ghanamail.com",
      "ghostmail.com",
      "giantsfan.com",
      "giga4u.de",
      "gigileung.org",
      "givepeaceachance.com",
      "glay.org",
      "glendale.net",
      "globalfree.it",
      "globalpagan.com",
      "globalsite.com.br",
      "globo.com",
      "globomail.com",
      "gmail.com",
      "gmx.at",
      "gmx.com",
      "gmx.de",

      "wwdg.com",
      "www.com",
      "www2000.net",
      "wx88.net",
      "wxs.net",
      "wyrm.supernews.com",
      "x-mail.net",
      "x-networks.net",
      "x5g.com",
      "xmastime.com",
      "xmsg.com",
      "xoom.com",
      "xoommail.com",
      "xpressmail.zzn.com",
      "xsmail.com",
      "xuno.com",
      "xzapmail.com",
      "ya.ru",
      "yada-yada.com",
      "yaho.com",
      "yahoo.ca",
      "yahoo.co.id",
      "yahoo.co.in",
      "yahoo.co.jp",
      "yahoo.co.kr",
      "yahoo.co.nz",
      "yahoo.co.uk",
      "yahoo.com",
      "yahoo.com.ar",
      "yahoo.com.au",
      "yahoo.com.br",
      "yahoo.com.cn",
      "yahoo.com.hk",

      "zcities.com",
      "zdnetmail.com",
      "zeeks.com",
      "zeepost.nl",
      "zensearch.net",
      "zhaowei.net",
      "zionweb.org",
      "zip.net",
      "zipido.com",
      "ziplink.net",
      "ziplip.com",
      "zipmail.com",
      "zipmail.com.br",
      "zipmax.com",
      "zmail.ru",
      "zoho.com",
      "zonnet.nl",
      "zoominternet.net",
      "zubee.com",
      "zuvio.com",
      "zuzzurello.com",
      "zwallet.com",
      "zybermail.com",
      "zydecofan.com",
      "zzn.com",
      "zzom.co.uk",
    ]
  }
}
